spring:
  config:
    activate:
      on-profile: uat
  jpa:
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/uatboot
  liquibase:
    enabled: false


logging:
  level:
    root: info
