spring:
  application:
    name: boot-shop
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

info:
  app:
    name: boot Shop
    author:
      name: Annahita

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: all




